### ISSUE TITLE
Build uncompressed file system images

### ISSUE THREAD

**Issue by psychemedia** [ouseful-testing/webr-package-repo-demo#1]
"webR < 0.4.1 does not support compressed filesystem images" so we need to set the build for the 0.3.3 version appropriately:

```yaml
jobs:
  deploy-cran-repo:
    uses: r-wasm/actions/.github/workflows/deploy-cran-repo.yml@v2
    with:
      webr-image: "ghcr.io/r-wasm/webr:v0.3.3"
      compress: false
```
